name: Docker Image CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build backend --file backend/Dockerfile --tag my-image-name:$(date +%s)

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/167456099297/locations/global/workloadIdentityPools/github-actions/providers/OIDC'
